name: 'execution_timer'
description: 'A library that makes it easy to determine how long snippets of code take to execute in real clock time.'
version: '1.0.3+4'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  flutter_lints: '^2.0.3'

dev_dependencies: 
  test: '^1.24.6'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
